# Action from the Github actions marketplace
# https://github.com/marketplace/actions/check-spelling-js-vue-html-markdown-text

name: Check Spelling
on:
  pull_request:
    paths:
    - '**.html'
    - '**.js'
    - '**.md'
    - '**.txt'
    - '**.vue'
    - '!overview/node_modules/**'
    - '!overview/.nuxt/**'
    - '!overview/plugins/**'
jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Spelling
      uses: UnicornGlobal/spellcheck-github-actions@master
